# index of each category given an array of used/unused categories
ONES = 0
TWOS = 1
THREES = 2
FOURS = 3
FIVES = 4
SIXES = 5
STRAIGHT = 6
FULL_HOUSE = 7
FOUR_OF_A_KIND = 8
GENERALA = 9

CATEGORIES = ['ONES', 'TWOS', 'THREES', 'FOURS', 'FIVES', 'SIXES', 'STRAIGHT', 'FULL-HOUSE', 'FOUR-OF-A-KIND', 'GENERALA']
NUM_CATEGORIES = len(CATEGORIES)